language: generic

cache:
  directories:
    - ${HOME}/.gem
    - node_modules

addons:
  apt:
    packages:
      - default-jdk

env:
  - PATH=${PATH}:${PWD}/node_modules/.bin

install:
  - bundle install --path ${HOME}/.gem
  - npm install

jobs:
  include:
    - stage: Lint
      script:
        - html-linter --config html-linter.json *.html

    - stage: Build
      script:
        - bundle exec jekyll build

    - stage: Build Android App
        script:
          - cordova create game-engine-demo io.github.example GameEngineDemo
          - cd game-engine-demo
          - cordova platform add android
          - cordova requirements
