language: generic

cache:
  directories:
    - ${HOME}/.gem

install:
  - bundle install --path ${HOME}/.gem
  - npm install npm jshint PrettyCSS js-beautify html-linter -g

jobs:
  include:
    - stage: Lint
      script:
        - bundle exec danger
        - html-linter --config html-linter.json *.html

    - stage: Build
      script:
        - bundle exec jekyll build
