language: generic

cache:
  directories:
    - ${HOME}/.gem
    - node_modules

install:
  - bundle install --path ${HOME}/.gem
  - npm install

jobs:
  include:
    - stage: Lint
      script:
        - bundle exec danger
        - ./node_modules/.bin/html-linter --config html-linter.json *.html

    - stage: Build
      script:
        - bundle exec jekyll build
